services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/management_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
        - db
  db:
    image: 'postgres:13'
    environment:
      - 'POSTGRES_DB=management_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: